### ISSUE TITLE
Command 'pip' not found, but there are 18 similar ones.

### ISSUE THREAD

**Issue by yus-run** [vLeeH/httpmapper#3]
pip install -r requirements.txt

**Command 'pip' not found, but there are 18 similar ones.**

**Python 3.8.5**

**Comment by vLeeH** [comment]
Try to use: pip3 install -r requirements.txt

If not works, you don't have pip installed.

**Comment by vLeeH** [comment]
> pip install -r requirements.txt
> 
> **Command 'pip' not found, but there are 18 similar ones.**
> 
> **Python 3.8.5**

Try to use: pip3 install -r requirements.txt

If not works, you don't have pip installed.
