### ISSUE TITLE
start()  function error !!

### ISSUE THREAD

**Issue by okkangal** [vLeeH/httpmapper#4]
When I select new consultation, I get error the "NameError: name 'start' is not defined" .   So, i researched the start() function in source code and I couldnt find it ....  
![Ekran görüntüsü 2021-04-24 212759](https://user-images.githubusercontent.com/3739573/115969120-0c70a480-a544-11eb-9418-9ff936ce2aae.png)

**Comment by vLeeH** [comment]
> When I select new consultation, I get error the "NameError: name 'start' is not defined" . So, i researched the start() function in source code and I couldnt find it ....
> ![Ekran görüntüsü 2021-04-24 212759](https://user-images.githubusercontent.com/3739573/115969120-0c70a480-a544-11eb-9418-9ff936ce2aae.png)

Thank for submitting this error. It has been corrected.
